// components/GlowCard.vue
<template>
  <div 
    class="relative group"
    :class="className"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
  >
    <!-- Glow effect background -->
    <div 
      class="absolute -inset-0.5 rounded-2xl opacity-0 group-hover:opacity-100 blur-lg transition-opacity duration-300"
      :class="glowClasses"
    />
    
    <!-- Card surface -->
    <div class="relative glass-surface rounded-2xl transform-gpu transition-all duration-200 ease-cosmic"
         :class="{ 'hover:scale-[1.02]': hover3d }">
      <!-- Gradient border overlay -->
      <div class="absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"
           style="background: var(--gradient-accent); padding: 1px;">
        <div class="w-full h-full bg-surface rounded-2xl"></div>
      </div>
      
      <!-- Shimmer overlay -->
      <div class="absolute inset-0 rounded-2xl overflow-hidden pointer-events-none">
        <div class="shimmer w-full h-full"></div>
      </div>
      
      <!-- Content -->
      <div class="relative z-10 p-8">
        <slot />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  className?: string
  glowIntensity?: 'low' | 'medium' | 'high'
  hover3d?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  className: '',
  glowIntensity: 'medium',
  hover3d: true
})

const glowClasses = computed(() => {
  const intensityMap = {
    low: 'bg-violet/20',
    medium: 'bg-gradient-to-r from-violet/30 to-magenta/30',
    high: 'bg-gradient-to-r from-violet/50 to-magenta/50'
  }
  return intensityMap[props.glowIntensity]
})

const handleMouseEnter = () => {
  // Optional: Add any mouse enter logic here
}

const handleMouseLeave = () => {
  // Optional: Add any mouse leave logic here
}
</script>

// src/components/GlowCard.tsx
import React, { ReactNode } from 'react';

interface GlowCardProps {
  children: ReactNode;
  className?: string;
  glowIntensity?: 'low' | 'medium' | 'high';
  hover3d?: boolean;
}

const GlowCard: React.FC<GlowCardProps> = ({ 
  children, 
  className = '', 
  glowIntensity = 'medium',
  hover3d = false 
}) => {
  const glowClasses = {
    low: 'group-hover:shadow-glow-violet/20',
    medium: 'group-hover:shadow-glow-violet/40',
    high: 'group-hover:shadow-glow-violet/60'
  };

  return (
    <div 
      className={`group cursor-pointer ${className}`}
      style={{ 
        transform: 'perspective(1000px) rotateX(0deg) rotateY(0deg)',
        transition: 'transform 0.2s ease-out',
      }}
      onMouseEnter={(e) => {
        if (hover3d && window.matchMedia('(prefers-reduced-motion: no-preference)').matches) {
          const rect = e.currentTarget.getBoundingClientRect();
          const x = (e.clientX - rect.left - rect.width / 2) / rect.width;
          const y = (e.clientY - rect.top - rect.height / 2) / rect.height;
          
          e.currentTarget.style.transform = 
            `perspective(1000px) rotateX(${-y * 3}deg) rotateY(${x * 3}deg) scale(1.02)`;
        }
      }}
      onMouseLeave={(e) => {
        if (hover3d) {
          e.currentTarget.style.transform = 
            'perspective(1000px) rotateX(0deg) rotateY(0deg) scale(1)';
        }
      }}
    >
      <div className={`
        glass-surface glass-hover rounded-2xl p-6 h-full relative overflow-hidden
        transform-gpu transition-all duration-200 ease-cosmic
        ${glowClasses[glowIntensity]}
      `}>
        {/* Gradient border overlay */}
        <div className="absolute inset-0 rounded-2xl bg-gradient-to-r from-violet to-magenta opacity-0 group-hover:opacity-10 transition-opacity duration-200 pointer-events-none" />
        
        {/* Shimmer effect */}
        <div className="absolute inset-0 rounded-2xl overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000" />
        </div>
        
        <div className="relative z-10">
          {children}
        </div>
      </div>
    </div>
  );
};

export default GlowCard;
