// components/ServicesCarousel.vue
<template>
  <div class="relative overflow-hidden">
    <!-- Gradient masks -->
    <div class="absolute left-0 top-0 bottom-0 w-24 bg-gradient-to-r from-bg-950 to-transparent z-10 pointer-events-none" />
    <div class="absolute right-0 top-0 bottom-0 w-24 bg-gradient-to-l from-bg-950 to-transparent z-10 pointer-events-none" />
    
    <!-- Carousel container -->
    <div 
      ref="scrollRef"
      class="flex gap-8 transition-transform duration-300 ease-cosmic py-8"
      :style="{ transform: `translateX(${translateX}px)` }"
    >
      <div
        v-for="(service, index) in services"
        :key="service.id"
        class="flex-shrink-0 w-80 transition-all duration-300 ease-cosmic transform-gpu"
        :class="getCardScale(index)"
        :style="{ zIndex: getCardZIndex(index) }"
      >
        <GlowCard 
          :glowIntensity="index === currentIndex ? 'high' : 'low'"
          class="h-full"
        >
          <div class="text-center space-y-6">
            <!-- Service Icon -->
            <div class="flex justify-center">
              <OrbitIcon :iconName="service.iconName" size="lg" />
            </div>
            
            <!-- Service Content -->
            <div>
              <h3 class="font-heading font-bold text-xl text-text-base mb-3">
                {{ service.title }}
              </h3>
              <p class="text-text-muted leading-relaxed mb-6">
                {{ service.description }}
              </p>
              <button class="inline-flex items-center gap-2 text-violet hover:text-magenta transition-colors duration-200 font-medium">
                Learn more
                <component :is="ArrowRightIcon" :size="16" />
              </button>
            </div>
          </div>
        </GlowCard>
      </div>
    </div>
    
    <!-- Navigation Controls -->
    <div class="flex justify-center items-center gap-4 mt-8">
      <!-- Previous Button -->
      <button
        @click="prevSlide"
        class="p-2 glass-surface glass-hover rounded-full focus-cosmic transition-all duration-200"
      >
        <component :is="ChevronLeftIcon" :size="20" class="text-text-base" />
      </button>
      
      <!-- Dot Indicators -->
      <div class="flex gap-2">
        <button
          v-for="(service, index) in services"
          :key="`dot-${service.id}`"
          @click="goToSlide(index)"
          class="w-2 h-2 rounded-full transition-all duration-200 focus-cosmic"
          :class="index === currentIndex ? 'bg-violet shadow-glow-violet' : 'bg-text-muted/30 hover:bg-text-muted/50'"
        />
      </div>
      
      <!-- Next Button -->
      <button
        @click="nextSlide"
        class="p-2 glass-surface glass-hover rounded-full focus-cosmic transition-all duration-200"
      >
        <component :is="ChevronRightIcon" :size="20" class="text-text-base" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Service {
  id: string
  title: string
  description: string
  iconName: string
}

const services: Service[] = [
  { id: '1', title: 'Birth Chart Analysis', description: 'Unlock the secrets written in the stars at your moment of birth', iconName: 'Sparkles' },
  { id: '2', title: 'Relationship Compatibility', description: 'Discover the cosmic chemistry between you and your partner', iconName: 'Target' },
  { id: '3', title: 'Career Path Guidance', description: 'Align your professional journey with celestial wisdom', iconName: 'Crown' },
]

const ArrowRightIcon = resolveComponent('IconArrowRight')
const ChevronLeftIcon = resolveComponent('IconChevronLeft') 
const ChevronRightIcon = resolveComponent('IconChevronRight')

const currentIndex = ref(1) // Start with middle item
const isAutoPlaying = ref(true)
const scrollRef = ref<HTMLDivElement>()
let autoPlayInterval: ReturnType<typeof setInterval> | undefined

const totalItems = services.length
const cardWidth = 320 // 80 * 4 (w-80 = 20rem = 320px) + gap

const translateX = computed(() => {
  const containerWidth = 1200 // Approximate container width
  const centerOffset = (containerWidth - cardWidth) / 2
  return centerOffset - (currentIndex.value * (cardWidth + 32)) // 32px gap
})

const goToSlide = (index: number) => {
  currentIndex.value = index
  resetAutoPlay()
}

const nextSlide = () => {
  currentIndex.value = (currentIndex.value + 1) % totalItems
  resetAutoPlay()
}

const prevSlide = () => {
  currentIndex.value = (currentIndex.value - 1 + totalItems) % totalItems
  resetAutoPlay()
}

const resetAutoPlay = () => {
  if (autoPlayInterval) {
    clearInterval(autoPlayInterval)
  }
  startAutoPlay()
}

const startAutoPlay = () => {
  if (!isAutoPlaying.value) return
  
  autoPlayInterval = setInterval(() => {
    nextSlide()
  }, 5000)
}

const getCardScale = (index: number) => {
  if (index === currentIndex.value) return 'scale-100 opacity-100'
  return 'scale-[0.94] opacity-[0.72]'
}

const getCardZIndex = (index: number) => {
  if (index === currentIndex.value) return 20
  return 10
}

onMounted(() => {
  startAutoPlay()
})

onUnmounted(() => {
  if (autoPlayInterval) {
    clearInterval(autoPlayInterval)
  }
})

// Pause auto-play on hover
const handleMouseEnter = () => {
  isAutoPlaying.value = false
  if (autoPlayInterval) {
    clearInterval(autoPlayInterval)
  }
}

const handleMouseLeave = () => {
  isAutoPlaying.value = true
  startAutoPlay()
}
</script>

// src/components/ServicesCarousel.tsx
import React, { useState, useRef, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Sparkles, Users, BookOpen, ArrowRight } from 'lucide-react';
import GlowCard from './GlowCard';

interface Service {
  id: string;
  title: string;
  description: string;
  Icon: typeof Sparkles;
}

const services: Service[] = [
  {
    id: '1',
    title: 'Personal Readings',
    description: 'Deep insights into your cosmic blueprint',
    Icon: Sparkles,
  },
  {
    id: '2',
    title: 'Relationship Analysis',
    description: 'Compatibility and connection guidance',
    Icon: Users,
  },
  {
    id: '3',
    title: 'Cosmic Education',
    description: 'Learn the ancient art of astrology',
    Icon: BookOpen,
  },
];

const ServicesCarousel: React.FC = () => {
  const [currentIndex, setCurrentIndex] = useState(1); // Start with middle item
  const [isAutoPlaying, setIsAutoPlaying] = useState(true);
  const scrollRef = useRef<HTMLDivElement>(null);
  const autoPlayRef = useRef<ReturnType<typeof setInterval>>();

  const totalItems = services.length;

  // Auto-play functionality
  useEffect(() => {
    if (isAutoPlaying) {
      autoPlayRef.current = setInterval(() => {
        setCurrentIndex((prev) => (prev + 1) % totalItems);
      }, 4000);
    }

    return () => {
      if (autoPlayRef.current) {
        clearInterval(autoPlayRef.current);
      }
    };
  }, [isAutoPlaying, totalItems]);

  const goToSlide = (index: number) => {
    setCurrentIndex(index);
    setIsAutoPlaying(false);
    setTimeout(() => setIsAutoPlaying(true), 5000);
  };

  const nextSlide = () => {
    goToSlide((currentIndex + 1) % totalItems);
  };

  const prevSlide = () => {
    goToSlide((currentIndex - 1 + totalItems) % totalItems);
  };

  const getCardScale = (index: number) => {
    if (index === currentIndex) return 'scale-100 opacity-100';
    return 'scale-[0.94] opacity-[0.72]';
  };

  const getCardZIndex = (index: number) => {
    return index === currentIndex ? 'z-20' : 'z-10';
  };

  return (
    <div className="relative w-full max-w-4xl mx-auto" role="region" aria-roledescription="carousel">
      <div className="relative h-80 overflow-hidden">
        {/* Gradient edge masks */}
        <div className="absolute left-0 top-0 w-20 h-full bg-gradient-to-r from-bg-950 to-transparent z-30 pointer-events-none" />
        <div className="absolute right-0 top-0 w-20 h-full bg-gradient-to-l from-bg-950 to-transparent z-30 pointer-events-none" />
        
        {/* Carousel container */}
        <div 
          ref={scrollRef}
          className="flex items-center justify-center h-full gap-8 transition-transform duration-500 ease-cosmic"
          style={{
            transform: `translateX(-${currentIndex * 320}px)`,
          }}
        >
          {services.map((service, index) => {
            const { Icon } = service;
            
            return (
              <div
                key={service.id}
                className={`
                  flex-shrink-0 w-80 transform-gpu transition-all duration-500 ease-cosmic
                  ${getCardScale(index)} ${getCardZIndex(index)}
                `}
                style={{
                  marginLeft: index === 0 ? '160px' : '0',
                  marginRight: index === services.length - 1 ? '160px' : '0',
                }}
              >
                <GlowCard hover3d className="h-full">
                  <div className="flex flex-col items-center text-center space-y-6">
                    <div className="relative">
                      <div className="w-16 h-16 rounded-full glass-surface flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
                        <Icon className="w-8 h-8 text-violet group-hover:text-magenta transition-colors duration-200" />
                      </div>
                      {index === currentIndex && (
                        <div className="absolute inset-0 rounded-full border-2 border-violet/30 animate-pulse" />
                      )}
                    </div>
                    
                    <div className="space-y-3">
                      <h3 className="text-xl font-heading font-bold text-text-base group-hover:gradient-text transition-all duration-200">
                        {service.title}
                      </h3>
                      <p className="text-text-muted leading-relaxed">
                        {service.description}
                      </p>
                    </div>
                    
                    <button className="inline-flex items-center space-x-2 text-violet hover:text-magenta transition-colors duration-200 font-medium group/btn">
                      <span>Learn more</span>
                      <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform duration-200" />
                    </button>
                  </div>
                </GlowCard>
              </div>
            );
          })}
        </div>
      </div>

      {/* Navigation arrows */}
      <button
        onClick={prevSlide}
        className="absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full glass-surface glass-hover flex items-center justify-center focus-cosmic group z-40"
        aria-label="Previous service"
      >
        <ChevronLeft className="w-5 h-5 text-text-base group-hover:text-violet transition-colors duration-200" />
      </button>
      
      <button
        onClick={nextSlide}
        className="absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full glass-surface glass-hover flex items-center justify-center focus-cosmic group z-40"
        aria-label="Next service"
      >
        <ChevronRight className="w-5 h-5 text-text-base group-hover:text-violet transition-colors duration-200" />
      </button>

      {/* Dots indicator */}
      <div className="flex justify-center space-x-2 mt-6">
        {services.map((_, index) => (
          <button
            key={index}
            onClick={() => goToSlide(index)}
            className={`
              w-2 h-2 rounded-full transition-all duration-200 focus-cosmic
              ${index === currentIndex 
                ? 'bg-gradient-to-r from-violet to-magenta shadow-glow-violet scale-125' 
                : 'bg-white/20 hover:bg-white/40'
              }
            `}
            aria-label={`Go to slide ${index + 1}`}
          />
        ))}
      </div>

      {/* Screen reader live region */}
      <div className="sr-only" aria-live="polite">
        Showing service {currentIndex + 1} of {totalItems}: {services[currentIndex]?.title}
      </div>
    </div>
  );
};

export default ServicesCarousel;
