// components/ZodiacBadge.vue
<template>
  <div 
    class="group relative p-6 glass-surface rounded-2xl tilt-hover shimmer transform-gpu transition-all duration-200 ease-cosmic hover:glow-violet opacity-0 translate-y-8"
    :class="{ 'animate-fade-in-up': isVisible }"
    :style="{ animationDelay: `${delay}ms` }"
  >
    <!-- Gradient border overlay -->
    <div class="absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"
         style="background: var(--gradient-accent); padding: 1px;">
      <div class="w-full h-full bg-bg-950 rounded-2xl"></div>
    </div>
    
    <!-- Content -->
    <div class="relative z-10 text-center space-y-4">
      <!-- Orbit Icon -->
      <div class="flex justify-center">
        <OrbitIcon :iconName="iconName" size="md" />
      </div>
      
      <!-- Badge Info -->
      <div>
        <h3 class="font-heading font-bold text-lg text-text-base mb-1">
          {{ name }}
        </h3>
        <p class="text-starlight text-sm font-medium mb-3">
          {{ dateRange }}
        </p>
        <p class="text-text-muted text-sm leading-relaxed">
          {{ description }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  name: string
  dateRange: string
  iconName: string
  description: string
  delay?: number
}

const props = withDefaults(defineProps<Props>(), {
  delay: 0
})

const isVisible = ref(false)
const badgeRef = ref<HTMLElement>()

onMounted(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          isVisible.value = true
        }
      })
    },
    { threshold: 0.1 }
  )

  if (badgeRef.value) {
    observer.observe(badgeRef.value)
  }

  onUnmounted(() => {
    observer.disconnect()
  })
})
</script>

<style scoped>
@keyframes fade-in-up {
  from {
    opacity: 0;
    transform: translateY(32px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-fade-in-up {
  animation: fade-in-up 0.6s ease-out forwards;
}
</style>

// src/components/ZodiacBadge.tsx
import React from 'react';
import { LucideIcon } from 'lucide-react';
import OrbitIcon from './OrbitIcon';

interface ZodiacBadgeProps {
  name: string;
  dateRange: string;
  Icon: LucideIcon;
  description: string;
}

const ZodiacBadge: React.FC<ZodiacBadgeProps> = ({ name, dateRange, Icon, description }) => {
  return (
    <div 
      className="group cursor-pointer transform-gpu transition-all duration-200 ease-cosmic hover:scale-105"
      style={{ 
        transform: 'perspective(1000px) rotateX(0deg) rotateY(0deg)',
        transition: 'transform 0.2s ease-out',
      }}
      onMouseEnter={(e) => {
        if (window.matchMedia('(prefers-reduced-motion: no-preference)').matches) {
          const rect = e.currentTarget.getBoundingClientRect();
          const x = (e.clientX - rect.left - rect.width / 2) / rect.width;
          const y = (e.clientY - rect.top - rect.height / 2) / rect.height;
          
          e.currentTarget.style.transform = 
            `perspective(1000px) rotateX(${-y * 4}deg) rotateY(${x * 4}deg) scale(1.02)`;
        }
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = 
          'perspective(1000px) rotateX(0deg) rotateY(0deg) scale(1)';
      }}
    >
      <div className="glass-surface glass-hover rounded-2xl p-6 h-full relative overflow-hidden group-hover:shadow-glow-violet">
        {/* Gradient border overlay */}
        <div className="absolute inset-0 rounded-2xl bg-gradient-to-r from-violet to-magenta opacity-0 group-hover:opacity-20 transition-opacity duration-200 pointer-events-none" />
        
        {/* Shimmer effect */}
        <div className="absolute inset-0 rounded-2xl overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000 shimmer" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center text-center space-y-4">
          <OrbitIcon Icon={Icon} size="lg" />
          
          <div className="space-y-1">
            <h3 className="font-heading font-bold text-text-base group-hover:gradient-text transition-all duration-200">
              {name}
            </h3>
            <p className="text-sm text-starlight font-medium">
              {dateRange}
            </p>
          </div>
          
          <p className="text-sm text-text-muted leading-relaxed">
            {description}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ZodiacBadge;
